eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/
      
spring:
  data:
    mongodb:
      password:  '{cipher}a52b286c66535f5d0aea8468a08b37ce2d1e0d7fa6fdab3f2f80e84e24aa80bb'
